#!/bin/sh
adduser --disabled-login  --home /home/%USER% --system  %USER%
addgroup %USER%
usermod -aG %USER% %USER%
mkdir /home/%USER%/.config
mkdir /home/%USER%/.config/pulse
chown -R %USER% /home/%USER%/.config
chgrp -R %USER% /home/%USER%
echo "default-server = unix:/tmp/%USER%-container-pulse" > /home/%USER%/.config/pulse/client.conf
chmod 770 -R /home/%USER%
echo "WARNING!EVERY DESKTOP USER WILL NOW HAVE AN ACCESS TO SANDBOX USER.TO PREVENT THIS RUN IN YOUR CONSOLE:"
echo "deluser (your untrusted user) %USER%"
cat /etc/passwd | awk -v val=$1 -F':' '( $3 >= 1000 ) {system("usermod -aG %USER% " $1)}'