#!/bin/sh
adduser --disabled-login  --home /home/%USER% --system  %USER%
addgroup %USER%
mkdir /home/%USER%/.config
mkdir /home/%USER%/.config/pulse
echo "default-server = unix:/tmp/%USER%-container-pulse" > /home/%USER%/.config/pulse/client.conf
cat /etc/passwd | awk -v val=$1 -F':' '( $3 >= 1000 ) {system("usermod -aG %USER% " $1)}'